---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token
  namespace: aiml
spec:
  secretStoreRef:
    name: openbao-labops
    kind: ClusterSecretStore
  target:
    name: hf-token
    creationPolicy: Owner
  refreshInterval: 1h
  data:
    - secretKey: token
      remoteRef:
        key: dan/aiml/hf-token
        property: token
