---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: intel-llm-api-key
  namespace: aiml
spec:
  encryptedData:
    api-key: AgDAqruzSrJGgn7yJp+Rj3skikaI6Wxbmf9LvPhLwgKuHd0mzbVQ0dR9mWejo4ifaBoNO9eKVbxsErmTBfXvTheelr3QdzDeHotdAlgYQbsDGnADcSnSGEbCLWEQdYrNiOR7EnRsUSBT82K1ThYghz3wKDtiSFz0tSe9su922ls3B+xXMYuiu1uqFcnIMJXDff6YWESmsaFiVbDTqkHKW/+SLdC2fzrVpquqQovKrgaFtLCLs3xVwUyAQoFEvkAgQW3EwdmeeXXzVi3HW1SAx/2TmMiG/DJyfhmeGODzQqPIDaI5Fp3Mf37Z8JNUPeFSCKUbD+B6Xivj3Q6r9jdXStfGSafrtNtHwwp025dGgnoaQHMnMjLlPeopGazpynuTuDw9dlaV0My0HkOiDzv+CPtl5H42DOrVBrXgTZoWe4Bd4R7UN8bkO4VwpMAszxYi8aoc2xrevvO3kPTiJEWGLoNFVUU2+rY4IDbPPzrYcGXhSyEC3Tv+GOeOtgSJUNi7BxsCMTwjSDSoerqNYOkxTPjT5nyy48CGaSCm3bQqhbpkVovTNs//pOFmt+NNsp4B3Y3x0y2GxYsNrwMGgrR+NE3zmcWmxLBLomF31hTdQMYcoEBLYDoFuXLWx+KL6CWVGJ9ubQLPe2WLjVkzyRDMEjRGpkY237wBsm1rlq8RBjKu5E0V6BW3KVvvmbylnI4BFvAI4eY9X46h0ZLJ3HS13F0ZREHz9P+JTliZ3x5duDA71qyHxwyVEhUBhTi1HEo75Z1gsJrs6Al4H4E6xI/EgkYI
  template:
    metadata:
      name: intel-llm-api-key
      namespace: aiml
