---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-superuser
  namespace: database
spec:
  encryptedData:
    password: AgACFD51iWnhHVsHovHa4ZZHGgGafLZoR8KRqvhHxL+brsSc06rAc283KACuKVzsU2yJVq91jyFFBigtYrSgAmY7nTokE+AuFkUdeU47WGuoaz7wIBw6XpiiLtR6k0jdhXk9pupsCuii1VCeqSeTPbuqyiLSxzzJeVW+3eUW4Gi0vwm947xJzoJW4T4CiV5/DFuuT5PkCuB3G+ZTU56su1SSpRShNzeU5fuyPI2QgB0agKC3GOq2zXFALBlXhj3Uk9maktEQbxrsHXFWNbc6swA+IdaiKWt/HOgdgXDgKx12s8QaqGDFaBX3T2bpIpgXDO/MVn/uw5LZfSC54KrLdn0CVAABqLtDc8Qbb0/QPPMSYKfg1/z3Xcav0nFUvHkA1QprS1UBKL/deh880UtCHAs5Cj26j5Ipf6T3idzUK1p5NLBg+QwYKZdOBnToZsEixycTvorKmCdASq70M/n50enXsm1JLDF+rrhtn4zEK+GTPgTeORSToAhVCPaet7YgdmgvBMHfisVpIOVFvFDvpcXqarZeS5OMGwVbhquQ73NFHdLwz1H5SyQ9Hyahklcpp/I/wETtMQiG737yHyhurg1/vpjVqYKbz5171Q6aoaNV+fIr7BbfvqlP+lj0ugCz/Mer9LLYF7LkcE+ZvCuSTK8se0cd1EaHlpdKyQjVfDvZgWlUbPZElC9Gz711+gZSpCDOBV31sY5s/HDJ1zxHynaGWDpa3K8eFJrWCOfHuVXcCIM=
    username: AgCF2pb/a7ZcAnW2/IMkzaMCP+A1RkWNcQ1DaWfttVacWEsFAUa7VGksZJ1B8VDWFwoAnMais5u9bci6vtXUjHgXS+I67EZbqFo7bvdp3gzENRfQLUJW3LR76Ud2kM4Pi6xXKHVGC6vf1XAOsIogmX/6KY5v/LMdktPWiJGxUNiLYRUbhRcNEummTHoPI91nQw3jPR/+x/VO9/nHZH44slZ0/2gXgT4CdJrX7DVyjLJcNTKNDV0ZM+cM0lZrg4tXFuw6bGzLjI2zMa0cgAqr6vFd1G5Mamhty5VWpn4E5Y2ufk0z/wXv8FhEVcAOpqM5DP9CEJQg5TowfKYt4aGy70sFp4Y73ttRYnf2uv8N/4XELNcvVoUiAkfOaE3oLPHboGFC5oufcrfqS3XrOLq23W0D9PcuyXYJozWfu4zEfY8Qs7myw5zTCXTp3+TPNxcOxyN5igBTT1ZC4k84T0YvKU2MraCm0lfMFlhGLOkHTByVbFfurqyNn8GHZqEnUwAVMSluGpGDC+voikTY0IM1HFpQJRXPWufz7mMjKpgVdEXEQ4uHNR7ln7X8tHVJqPxATQIm7M5I99JW0ZbxWKjIrxv2wG9YLa28gQXsnxJxWyt0EXf2shlS4+DFhSqiId82V9q1x34t+dUTWS+BgmO3d1D6xUC7YSyZrb5Kv45Nni1aG6l2YYH7DAZsM1od42640oMt3rW3CoYciQ==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      creationTimestamp: null
      name: database-superuser
      namespace: database
    type: Opaque
