apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.cloud.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  name: argocd-extname
  namespace: argocd
spec:
  externalName: unifi-home.homelab.danmanners.com
  sessionAffinity: None
  type: ExternalName
