apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gwapi
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.capi-core.homelab.danmanners.com"
    allowedRoutes:
      namespaces:
        from: All
  - name: http-cloud
    protocol: HTTP
    port: 80
    hostname: "*.cloud.danmanners.com"
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.capi-core.homelab.danmanners.com"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard
        kind: Secret
        group: ""
  - name: https-cloud
    protocol: HTTPS
    port: 443
    hostname: "*.cloud.danmanners.com"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard
        kind: Secret
        group: ""
