apiVersion: v1
kind: ConfigMap
metadata:
  name: gwapi-gw-options
  namespace: default
data:
  deployment: |
    spec:
      replicas: 2
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      gateway.networking.k8s.io/gateway-name: gwapi
                  topologyKey: kubernetes.io/hostname
  podDisruptionBudget: |
    spec:
      minAvailable: 1
