---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
spec:
  hostnames:
  - harbor.cloud.danmanners.com
  parentRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: gwapi
    namespace: default
    sectionName: https-cloud
  rules:
  - name: harbor
    backendRefs:
    - name: harbor
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
    timeouts:
      backendRequest: 0s
      request: 0s

# ---
# apiVersion: gateway.networking.k8s.io/v1alpha2
# kind: TLSRoute
# metadata:
#   name: harbor
# spec:
#   hostnames:
#   - harbor.cloud.danmanners.com
#   parentRefs:
#   - kind: Gateway
#     group: gateway.networking.k8s.io
#     name: gwapi
#     namespace: default
#     sectionName: harbor
#   rules:
#   - name: harbor-portal
#     backendRefs:
#     - group: ""
#       kind: Service
#       name: harbor
#       port: 443
#       weight: 1
