---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
  annotations:
    external-dns.alpha.kubernetes.io/controller: "false"
    gatus.home-operations.com/enabled: "true"
    gatus.home-operations.com/endpoint: |-
      name: Harbor
      conditions:
        - "[STATUS] == 200"
      url: http://harbor.cloud.danmanners.com
      method: HEAD
spec:
  hostnames:
    - harbor.cloud.danmanners.com
  parentRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: gwapi
      namespace: default
      sectionName: https-cloud
  rules:
    - name: harbor
      backendRefs:
        - group: ""
          kind: Service
          name: harbor
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        backendRequest: 0s
        request: 0s
