namespace: gaming
resources:
- secret.windrose.yaml

configMapGenerator:
  - name: windrose-configmap
    files:
      - config.json=./config.json
      - ServerDescription.json=./ServerDescription.json

generatorOptions:
  disableNameSuffixHash: true