---
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: true
  restartPolicy: Always

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    containers:
      iperf:
        ports:
          - name: iperf-tcp
            containerPort: 5201
            protocol: TCP
          - name: iperf-udp
            containerPort: 5201
            protocol: UDP
        image:
          repository: docker.io/networkstatic/iperf3@sha256
          tag: "993080f3167738f4155d6b2749b8b95ba6da5d44fe1c02e36b6e03a6d544c922"
          pullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
        args:
          - "--server"
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 1Gi
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: LoadBalancer
    ports:
      tcp:
        enabled: true
        port: 5201
        targetPort: iperf-tcp
        protocol: TCP
      udp:
        enabled: true
        port: 5201
        targetPort: iperf-udp
        protocol: UDP

rawResources:
  namespace:
    enabled: true
    apiVersion: v1
    kind: Namespace
    spec: {}
