---
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: true
  restartPolicy: Always

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    containers:
      core:
        ports:
        - name: iperf
          containerPort: 5201
          protocol: TCP
        image:
          repository: docker.io/networkstatic/iperf3
          tag: "latest"
          pullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
        args:
        - "--server"
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 1Gi
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: LoadBalancer
    ports:
      tcp:
        enabled: true
        port: 5201
        targetPort: iperf
        protocol: TCP

rawResources:
  namespace:
    enabled: true
    apiVersion: v1
    kind: Namespace
    spec: {}
