apiVersion: v1
kind: Secret
metadata:
  name: envoy-gateway-oci
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: docker.io/envoyproxy
  name: envoy-gateway
  type: helm
  enableOCI: "true"
