apiVersion: v1
kind: Secret
metadata:
  name: home-operations-charts-upstream-oci
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ghcr.io/home-operations/charts
  name: home-operations-charts
  type: helm
  enableOCI: "true"
