apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: route53-credentials
  namespace: kube-system
spec:
  secretStoreRef:
    name: openbao-labops
    kind: ClusterSecretStore
  refreshInterval: 30m
  target:
    name: route53-credentials
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws/creds/external-dns
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws/creds/external-dns
        property: secret_key
    - secretKey: AWS_SESSION_TOKEN
      remoteRef:
        key: aws/creds/external-dns
        property: session_token
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: aws/creds/external-dns
        property: region
