fullnameOverride: "arc"
replicaCount: 1

image:
  repository: "ghcr.io/actions/gha-runner-scale-set-controller"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

flags:
  logLevel: "error"
  logFormat: "json"
  runnerMaxConcurrentReconciles: 4
  updateStrategy: "eventual"
  excludeLabelPropagationPrefixes:
  - "argocd.argoproj.io/instance"

k8sClientRateLimiterQPS: 20
k8sClientRateLimiterBurst: 30
