apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-clients-as
  namespace: powerdns
data:
  pdns.conf: |
    config-name=as-1
    local-address=0.0.0.0
    local-port=5353
    loglevel=6
    query-logging=yes
    version-string=powerdns
    webserver-loglevel=normal
    webserver-allow-from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    webserver-address=0.0.0.0
    webserver=yes
    api=yes
    api-key=$scrypt$ln=10,p=1,r=8$AGpU17fet8kfDSRPws0aXQ==$vVwUQLrGDCxWSuelBlkdjtZkl+6O+LinSebDIwp4skE=
