---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-dns
  namespace: powerdns
  labels:
    app: powerdns-clients-as
spec:
  ports:
  - name: pwds-as-tcp
    protocol: TCP
    port: 53
    targetPort: 5353
  - name: pwds-as-udp
    protocol: UDP
    port: 53
    targetPort: 5353
  selector:
    app: powerdns-clients-as
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-gui
  namespace: powerdns
  labels:
    app: powerdns-clients-as
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pdns.capi-core.homelab.danmanners.com
spec:
  ports:
  - name: pwds-as-web
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: powerdns-clients-as
  type: LoadBalancer
  sessionAffinity: None
