---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: as-secrets
  namespace: powerdns
spec:
  encryptedData:
    ci-job-id: AgBCVdJT+ms0NTzKyZIj/4zPizA74SzWz5Hl6ajLZj8pVSMt0Q49YzHZuMjtfS1Og79DW2tUsP8vGi4gmZ46SZMQYjvXz2koQ5DHbbQ1Wg22CadJ4ht5oVpgCxxf4SKFtfhFh2j2UEZywTnT9qbtdIuVcoNYyS8ILKNeZx8bo4ff6xEGX9UoMqK7cslkHNalWLJzA4xgSjOru9kxLHMpJ4SQWNk9ecOJWWRBtq5AzJjhz52sjxHqL4FoZblYcjjXG8KJ9E+w+tMZf5bBQbQBbA1gvbUuuf/uYPTbnG8AaGHUNMsqLAKBonKJ84WjoXizM4Uo5qOKvtbiuRWQELoRbx2NIM4/0TY8k2Ok//2zokqhTbyRUE4XpUGh6dAJwxrZiivTtIdb3yA1u3b/XyhiNZZKFxigydzdoI+5pkkyjt2a/lJoq0aLK7f+Vi4aEGL0Rktiw2ni0qbOoJDxdpDsWONlGcj/vauexoL1wOQrZalDPdJx/9EWZEqCo7bmd3mtHCCKAlq5ddTi2iJ5jHOuGVFxP0KqoTzCg3CZKMCMhpQrdszxVvaxTiuEEN624RuVioFwki4sVkvprb4J+HP2iB8BwkgeHwIaWDBXYjD9dde+5eHpS70YdxzczyH2vx3v5L+n+GMeblwVk1qFbg28RIEhjTi66bRyFE8wGWSdh0lumHwX9NABiy5KmyM2BpdUvlg0H2+npoBP/3zU2XF7BKoUKEobTlVM1MXTs38Ifiq0RA==
    key: AgBcsvpx+7XQ/AW5y0Z/+T9JZtAOaZpyYB2tnO6EAwJ4ziiijvhhrVDjjPGeAudqQvcfH5C0nycWuXXx6miiBZV7CYudFSPZWHC6Whj+U/CV1JAOJpY2rY5Zf3Z6BUJxAtmJo85M9HSONSSR6HM3nEV26E9MuNbOBwBb8jQbI3DEGbNxHc2TNc19Ut7LfpFpjy3eapBP/396bk1nWlqj81pLzpAlANsr9zDV/lRSWOeSU0/obcZRPAGzAZ6a8dI4wrD/tRa7hmFUe8n5ivDL94XZzBzNaolLfTySdcm7D9GQu09nUkhB7UHDcFaI3eqVWzfL4udggyOOYshhO/lJM6v2jQYKPmYRf3kdUOgNvxI9ML46D/RpfsDwY+mqkuWxBc1d9dcuPzbD8yNMHD+c8butQ6h0/omXUBxoSpacqlWkYq2yH8dh7LX7dqpFPka3wG6L1xKI7629rol40gNax3R7VawNq17N/P9CNzg1iGMGw/FMh8PRa8xAWD9tqZFKU/KGFS9tARA3WrfqKV5evVS0r//9aMh4/5dyq3g/YcoW3pBeXR+/fshWtK2/fmAvbR4bLoP8x3N9210pbk4UvEKA1LES8Vt0Z0v9c+6OBvBTwN+gqA3mWCZZzTrL62bOFiHOMZf0mW1d1XuCEBcuwYGUOWKAiJlCdvZFCP5/hVWv0a5Yk+8atXu++Vb106SiKhJfgdFlDupfFfvO4zSlm2tVwmS5XoloijjsRQ9+SnSDHtEf+Tz02I8n8mIKYfbfqBhzM2ILQeZGFE4sOe9eMnXlsQa72WJYlL1hs3cOfsGoT9gM1blxlh4Y0zClTPgC+tyETVc5G+3K0XM1t5cUqb+S9TMG5oVw0Hb0qamWGbljnQ==
  template:
    metadata:
      creationTimestamp: null
      name: as-secrets
      namespace: powerdns
    type: Opaque
