apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: powerdns

resources:
- namespace.yaml
- as-cm.yaml
- as-deployment.yaml
- as-job.yaml
- as-secret.yaml
- as-services.yaml
- sqlite3-storage.yaml
