apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-sqlite3-db
  namespace: powerdns
  labels:
    app: powerdns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs-retain
