apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-core-internal-tls
  namespace: keycloak
spec:
  secretName: keycloak-core-internal-tls
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  dnsNames:
  - keycloak-core
  - keycloak-core.keycloak.svc
  - keycloak-core.keycloak.svc.cluster.local
  - 127.0.0.1
  issuerRef:
    kind: Issuer
    name: keycloak-internal-ca-issuer
