---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api
  namespace: argocd
  labels:
    # renovate: datasource=helm chartLocation=https://kubernetes-sigs.github.io/cluster-api-operator chart=cluster-api-operator
    chartVersion: &chartVersion 0.19.0
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ""
  project: default
  sources:
  - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
    targetRevision: &tr main
    path: kubernetes/cluster-api
  - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
    targetRevision: *tr
    ref: values
  - repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    chart: cluster-api-operator
    targetRevision: *chartVersion
    helm:
      valueFiles:
      - $values/kubernetes/cluster-api/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
