---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: education-projects
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
      targetRevision: main
      path: kubernetes/projects
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
