---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  labels:
    chartVersion: &chartVersion v1.4.2
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: docker.io/envoyproxy
    targetRevision: *chartVersion
    chart: gateway-helm
  - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
    targetRevision: main
    path: kubernetes/core/envoy-gateway
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
