---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    # renovate: datasource=helm chartLocation=https://kubernetes-sigs.github.io/external-dns/ chart=external-dns
    chartVersion: &chartVersion 1.18.0
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
    targetRevision: main
    ref: values
  - repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: *chartVersion
    helm:
      valueFiles:
      - $values/kubernetes/core/kube-system/external-dns/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
