---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    chartVersion: &chartVersion 2.10.0
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
      targetRevision: main
      path: kubernetes/core/external-secrets
      ref: values
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: *chartVersion
      helm:
        valueFiles:
          - $values/kubernetes/core/external-secrets/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
