---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    chartVersion: &chartVersion 4.1.2
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: &repo https://github.com/GoodMannersHosting/home-enterprise-labops.git
    targetRevision: main
    path: kubernetes/core/keycloak
  - repoURL: *repo
    targetRevision: main
    ref: values
  - repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: *chartVersion
    helm:
      valueFiles:
      - $values/kubernetes/core/keycloak/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
