---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kopiur
  namespace: argocd
  labels:
    chartVersion: &chartVersion 0.8.1
spec:
  destination:
    namespace: kopiur-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/home-operations/kopiur.git
      targetRevision: *chartVersion
      path: deploy/helm/kopiur
      helm:
        valueFiles:
          - $values/kubernetes/core/kopiur/values.kopiur.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
