---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-csr-approver
  namespace: argocd
  labels:
    chartVersion: &chartVersion 1.2.15
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
      targetRevision: main
      ref: values
    - repoURL: https://postfinance.github.io/kubelet-csr-approver
      chart: kubelet-csr-approver
      targetRevision: *chartVersion
      helm:
        valueFiles:
          - $values/kubernetes/core/kube-system/kubelet-csr-approver/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
