---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
  labels:
    chartVersion: &chartVersion 0.17.3
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    chart: node-feature-discovery
    targetRevision: *chartVersion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
