---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
  labels:
    # renovate: datasource=helm chartLocation=https://openbao.github.io/helm chart=openbao
    chartVersion: &chartVersion 0.12.0
spec:
  destination:
    namespace: openbao
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
    targetRevision: main
    ref: values
  - repoURL: https://openbao.github.io/openbao-helm
    chart: openbao
    targetRevision: *chartVersion
    helm:
      valueFiles:
      - $values/kubernetes/core/openbao/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
