config:
  map:
    default: |-
      version: v1
      flags:
        migStrategy: none
    mig-single: |-
      version: v1
      flags:
        migStrategy: single
    mig-mixed: |-
      version: v1
      flags:
        migStrategy: mixed
  # Default config name within the ConfigMap
  default: "default"
  # List of fallback strategies to attempt if no config is selected and no default is provided
  fallbackStrategies: [ "named", "single" ]
runtimeClassName: nvidia
nodeSelector:
  feature.node.kubernetes.io/pci-0300_10de.present: "true"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        # On discrete-GPU based systems NFD adds the following label where 10de is the NVIDIA PCI vendor ID
        - key: feature.node.kubernetes.io/pci-0300_10de.present
          operator: In
          values:
          - "true"
      - matchExpressions:
        # We allow a GPU deployment to be forced by setting the following label to "true"
        - key: "nvidia.com/gpu.present"
          operator: In
          values:
          - "true"
nfd: {}
gfd:
  enabled: false
