apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aiml

resources:
  - librechat-secrets.yaml

configMapGenerator:
  - name: librechat-config
    files:
      - librechat.yaml=./librechat.yaml

generatorOptions:
  disableNameSuffixHash: true
