# Operator RBAC (Cluster-scoped resources, don't inherit kustomize namespace transform)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meticulous-operator
rules:
- apiGroups: ["meticulous.dev"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["meticulous.dev"]
  resources: ["agentpools/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meticulous-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meticulous-operator
subjects:
- kind: ServiceAccount
  name: meticulous-operator
  namespace: meticulous
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meticulous-operator
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: met-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: met-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: met-operator
    spec:
      automountServiceAccountToken: true
      serviceAccountName: meticulous-operator
      hostAliases:
        - ip: "172.31.0.10"
          hostnames:
            - "keycloak.cloud.danmanners.com"
            - "harbor.cloud.danmanners.com"
      containers:
        - name: operator
          image: harbor.cloud.danmanners.com/meticulous/met-operator:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
