---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meticulous-db-owner
  namespace: meticulous
spec:
  encryptedData:
    password: AgCjEgopDnNwLzYX++x3CF51+MImBA+E1//X46/QjbdHq1LHREkUhQ0zqPFZU8kcJmCBSKfadgT1nAVuiFDUv/uuc6PYJsOJX15ZJdOH5jShyJJdU1DXKq5lBrVzZewnMlGgmQCHK4D0jGlBYJ9Rq4LQ6FoYBMP3plETbMMN67/xx+Oh7u3PEQGc3ov6T351LiywnsZmc9Ii+V06f1bjLHALGBfk2bQNx+9Rm2OEEw2uShAN/E+squPyvmJvf56G7oH7fzQCuUvNYwR7JUlAiA2UyUZu3vwjLvQSHXuVx9tP9Tan7mbS+M1LQeMZ9SeWKXdIyrU+9sQKrLcksfaa0Si3xUmnFgZiulqeh6jbu9IkdgqTJNnSqM9YJ1fhctlNWCbVo+o2MLAHz2s4UDN0vIpJ0pUUDjeV5eO/j+NdtmMLaySL058Yg6ofVxc3sCkwPm05leGL1QPYzoQVmvJn7ReHZ5YbeSfPOzYLSEYocdGaFBVPYRS0RZ/jZvhyDvt8mOLrnSY6xIgU4n+DCqI4J7uYmcnmpquyJEstYFd/L4l/kQwdg2PDALCfFGQUbMEdpsMjt7Xzy6TsmpKnk+/L4AIrVG164Edpc935yZodMv5sQCaXSd5mscRMbgiSc2ngC1ynoxQNLNcD9JGZnqFGwuMIIitb+MmzBILbohj7JM77fSxaFr55D7piP89Zu4pwBs2NrlzIogzWtReBQTMcusx+slzYKI71SXtA/9R7OZz2iLhZn4fBri671xaA8Q==
    username: AgA1dzJ/xyb3vfUkz+o/ptMf3gbJet7KAF6fdkZEg4Zw2c7zVoGPzp4k+CTOXMGqBWitoZD4KnuXsBTQtPdfKsGzONnVqlMa7kGGKngCM3JEp5Xm6LvcxI9FSYxGZT25POAqeA4ZZjLums14NBPYKP4Se/ovF9xif9TobSItHB09uHycxYAlKLaBQ3wZJdJgUtInZwdCXVMrFfAfLwR0V0ptpXx1o3mi8D+K4Gg+MzsvV7S3ENnMr3GAFtXWrqBT8r/x53AU4K+/TkSPmF2kwt2i+OvyNXafLfQXtLWsmTDph0LixixetRBS04HZZS1b/NHEaYW3FVTQdTEoo8WaSAp6tACjL3c1kX34y0eVf3OYrKLY2U/zfmiOb7IuW3URDQybjmYjoWg7gcG75cIHIlyQZDDTBbzwmLOV7RcuYuIGuDBBDC27SPE8xgfgTrdxA3EAyNIXUh66RWDtZNs3abDBkRhgzBod+87eOZHRaZ+iE0MsSo1dATQyU9A2aAS+/NJTnrJB5A/dHZyI4nC7Etan3ZQDYNupxglhvYNZYJmIv3aUkzRVdAxcr4XDgMpdLdR9dtKzVxuOHAK5hXSu47bpEyAwUAdBfQHr9CXEYi0c9plAjd4rwcchhCa35D7IQ9wf9TOxmWuB5wn7dzGfJ0cSpgOzduN/fVL9pVxd9zXIm8gapx94KoyCDUMczneTyUO66f5VzIO3fj70
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: meticulous-db-owner
      namespace: meticulous
