---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meticulous-db-uri
  namespace: meticulous
spec:
  encryptedData:
    uri: AgAaB22EcYY0cGcbE9my5lMJE2EHewH8udGW4e/rppDqIlcwjWcDfgNmU+2o02g+iSJJ/rrggi0GZ10J1EwZWrUsDjS+PHX0z/ZXTQ4ORxaIIV0P5U8BtgOgT/MeT+VJnjg8zAr7Fq6u453AGPwMe9jts8CdgQ2MsZL4QOr9+ux89WUE+eL58qF2GpniBnJROXeJkB2pbPthuNyuU2erdeea1Bhtj28haNRQ6HsuYh/g8b8igV31aQgHqB19FIgtwQKrcVPxUmK7m7rBxm9ySsbW17UXraJlw+jbaGg/Yj95+/nN3zV8EFQ+RXmCgT2Kq/0XSxxSvori7TWukaLAfcgisUe+jDGFenszCxYtrvxWaT0fGytOQQJaBYqDR46DjFYhZxbcjcb01NHj1hkRaSSGl6UIVAkNm04FkcP1YhGPJmoaX+lE3apRPwXfyOn2aYASITU6dGbXY+bD7dRyh7QKe8S4IL90fr75wwF5sfMYpBvC2RvfDWccf3ESIeyfhCBIQJn2eSsKIoYr8Pjyx1GF0uTch8YWhvVVusGAqGG5aAGt1aTut1Og/xvHdrgiCXFZdxaEDCBRlVRhjVqIRoKUoiIipL3z5g6L5sST8cdfCVRCG4W7BU79UKrZHGBwzgR0Qv0sXGmdnmeE2GAOZ61Mb7hy3jM77uS92oJAg36duBlWEL20HGlmHP6UQu/nlUvwIw0JG551GTgUK7q7WjJnjP31Z8L/MI/+47jzdY5eP4wlZ3yBAeV4kkaVJQFIld5XGQO1Sw1VWpNMJDYYry0XtTWdobJ3gmvbe740exJtRj4xrjKTcBiEhLYAZTyOJbvk3CpnJOxN
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: meticulous-db-uri
      namespace: meticulous
