---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meticulous-db-owner
  namespace: meticulous
spec:
  encryptedData:
    password: AgBVt231KL8l98+jyleVy0dM6OeIeUX26IkRd0jwOoIC5EvocBMcdYasDAPxZcoXIk5ySstidhN1OnNVPijZOM9hbSnxvD3CzlYyIZJQE6fcY49Bbw6DDCpVpXyfim+rDghVX3dCQqVmmkVOu+SOg71e6tBfvNV0rgJ4b1rVXEqsmR69ZSoQ1Ypy0KkWPkBK2X4+SVh4zD1lDoXtGz16AZcpbUChP0LKdY2xUtYHbHv4bQgw8c0zXaqNDDNIf91juCYSLqcwSaQbzTJQ4sFA9gUHcFyIqz05lsc/+VApK6ifCAJHuM58BDZoL4dqfXgEnvNfLsbQnRwY0CTJ120xoic/7DiEvuPaU46Df++2bEG1FMyv1VWc7gw4QZQIWv6EXODjlcqziGbJMDwVjF23kRmQ+v9S7qBtl4l53EV/PwJwNvk7v9CQy0WxwKb3Mf+f2cl6gWiBqVF9/DBW4Bb+zuN7NrfFipwv7xFO4D5qp8FAkfrBoiRrJzdVCw0ulGAheZRlsuXpDvPwlQPfJDn1busqcRdedOf3yNBb/P323QC5THwK9X0+q5pvMuol5Tzh6EiRO53VdJAQcxDF2Ur6MiD1xkLMnqZua8NTDO4ulRERCq6MfRHM2+U5FdMQ9WGgkrs+H4qhvt1hpuI4d+OlO6pRe2m8abkOhzh/7zl5c4QdDhqYMdY4BHA+BnbCEQEE+mQA3UbkVPp6NE4lak9uas5YF5YJ8PPhdPdinCQozrOifzUJxRrcUH316tgxsw==
    username: AgAIjfMe+DM88oaqUIKqBfRG68UdtdJnbPcULJuFS9BEuKgLBAg39x+t42iZowIAJLq0c6SGSYvgbWQmgipE2q1rzjk/FjSbyU6eYXHEFiOCUBFbJ8UTDTGhZ6ZMIoIZP8FuRIEpfCjjqmCJsEvAeb+CDEtxTZVUiFZOqV+JVnGQUXekOliPMvKqm4eqczvPTGmWyegvZTZZJ85S8oSbwvoQP1Bu/bLZ24YmQhX0ocaYju5UBJ4d0KFkqvPRpuNqpP8F2BVNwAw+NQ4kwE/7pTnKK5Iv5ANqVfuuyVpG1OLICR54nRt+2zDyxLoaHzS4A5c3twPKNc4uSQvNkF9EvhZs3AKjBUzHqTk4gXVaKnEGHSX1ImYaLraMWhHhJ1cChPzoTLisoDt6xPWLA4OuCCavdwRApdPBIa5LCMZ9xlWpEJnefNbRZjGZPX4jINrR1S1yopSyJWqoB+bw+OXnrx9ex0IClK3BGU+xMtCaNVnjXs4++TKpfZ5bkRqzYs10VcSee+QUxGi+YzvVtM268dBr/kJDET8aJwleQpT2Q2Qsbxxz+nrAJNufFXV1lZeXJegDtCx6PayVAa2rwnH9E8I648ka786o9ndc+RjJMnLHB/OU19oeuiMN2c/tw+9uy8qSx8I39aOvnpdOJ1C6LKeXQvi3HO7g2rrpaci+H7V9cHAGNWpi5WPHclm3rhdET1WFxOMl3rmqWVbf
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: meticulous-db-owner
      namespace: meticulous
