---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-labops
spec:
  provider:
    vault:
      server: https://keeper.goodmanners.services
      namespace: homelab-dan
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-labops
          role: labops-eso
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
