---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-secret
  namespace: aiml
spec:
  encryptedData:
    token: AgCCdc58Suz0U/UnxOuO41BCWFwBRwjR1qsg8FD5DBFwDjX9QdNHj2BGcSmA2L37yRHlNJwLJd41nn7owgR+lPUCPpIyI90NlU6TqXeZmCerSbWi/31RtdNUWn5GNFc1NRfZ57BQd3XlAF+Zp1HLnppw7Ns9HeMHs0naJXjCfFt1K2N3a6fUioY+cWrRVzm2MH6F7ZY765kZ9s7otSAtEu9BiuvO4dmENJo6ENhDEw8u/GL/7dZ+WVzOiSpbuTpAJtpjM0erTSIB9tucl1namomtLwFHhFIC/ibJ6zoi+KEqlh44t9Ge1nbMNrJYGe0+NoYO6YJRMbV3CGAPIE4akYKl6m6fnopZSELnYZHC5EAIFz3Q1SsKgqOI2f85CXrYZq3cEopd1nkEriVZ30MYvUlhEAECTuh+W7p51z1y+Y4nVjZ7sHS/QNs4rdgkuUpUQjn3JPROjJo09uyhJty26JT0N2tpCq6NE3SaLa1204kUDWpJfk2RoY+AGkJb6iNrI9QYtURaCKpZxFtOVdhYQhu1WIDBEi1e5xviI7Dm9ypUNHivDzjV8tMJQQVeXmUJ4aA3usV5YtfdLfBoRcMvdChGUQY8WBduFXcj/uPWIS8SZRad+51nA/rXyecutkwiJ1MVJwFsq+KeVCCLIu+L2HC/HBKVN5WBOmx5krIZ92b6R7AgtJpTyR1WetrUh4Di/g2/PdRkTzUxC8GNsmyikEX+I/HBU+qFBr4Up89oq31M+7J4lHW/
  template:
    metadata:
      name: hf-secret
      namespace: aiml
    type: Opaque
