---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oidc-secret
  namespace: aiml
spec:
  encryptedData:
    clientSecret: AgAfIZlzQLQcl+CCcg/gFPy8g6BAKnDNxhaG4uBi6EFarGynhhb214TSVfxdOpefym7GUpiblRJP1P1uiKUL3WSA6mUpHoGhiYwoOmBuxn7c5sNDHZ2f+VTQOZ4TIKcb9XQaq8h+gWit3ZSxMpzpicO2cmXDtiRqZjcYVuxCHapj7ptIRHkzeUAVzpEMjbrChWDwSveKSlWSQJyFnz2ASxJPoOcE3rxikb1ykvBUC9bUAbnZLeq0QeQyi5ICAGCl7aP4HQ4lFXZKyCb99+JH/4mtxutgiTavGYLAmuoJMwA0o2z/g8WJLIr04T6h35E1TUCE4wPik/sPVtoSqaY0MwzmO8mNK/59XNhiJlIgurqwFFsW8ZjgBscgg+1/XXxZ5Jsy4ze/l9MKuJpadi6gKjZHV9/08GR0c2gVqXXss8jjq1ms3eLmd+g0KkJ9wuoJm0eiusgwAildmyUJgRzFTUdU1Ag6zwhnZvtx/0kTKlr1oelpbU2qD5vsVEVXRZ49OV7zQjIVAOLAyLp4TCNPZtVjujJ67B0vIi7hp8kuWnRRal4FMvq+fWxmGH6wNauhyLXLXulzBmadpIYiDdusoPGf1C3kPFtWukxUWbJ4G1t/7Uh3QNPtaVQC7t3vnixWgpe9Vi7QIA6dwO9LUW6hjT7efjjxaLXd6ICV1c22d32/xvRqJuBiVo2wc7ultLHcy2HYhoRg1Yz2QRE4p3js0GFUlEuUasRy++kQFTMYEf5GDw==
  template:
    metadata:
      name: open-webui-oidc-secret
      namespace: aiml
