nameOverride: ""
namespaceOverride: ""
ollama:
  name: "ollama"
  enabled: true
  fullnameOverride: ""
  resources:
    requests:
      nvidia.com/gpu: "1"
    limits:
      memory: "8Gi"
      cpu: "2"
      nvidia.com/gpu: "1"
  ollama:
    gpu:
      enabled: true
      type: nvidia
    models:
      pull: []
      run: []
  image:
    tag: "0.12.6"
    pullPolicy: "Always"
  extraEnv:
    - name: "OLLAMA_NUM_PARALLEL"
      value: "2"
    - name: "OLLAMA_FLASH_ATTENTION"
      value: "1"
    - name: "OLLAMA_MAX_LOADED_MODELS"
      value: "1"
    # - name: "OLLAMA_KV_CACHE_TYPE"
    #   value: "q8_0"
  runtimeClassName: nvidia
  persistentVolume:
    enabled: true
    size: 240Gi
    storageClass: ceph-block-retain
    accessModes:
      - ReadWriteOnce
  service:
    annotations:
      gatus.home-operations.com/enabled: "true"
      gatus.home-operations.com/endpoint: |-
        name: Ollama (Internal)
        conditions:
          - "[STATUS] == 200"
        url: http://ollama.aiml.svc.cluster.local:11434
        method: GET

pipelines:
  enabled: false

# -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
# ollamaUrls: [ "https://ollama.cloud.danmanners.com" ]
clusterDomain: cluster.local

image:
  repository: ghcr.io/open-webui/open-webui
  tag: "0.6.34"
  pullPolicy: "IfNotPresent"

serviceAccount:
  enable: true

managedCertificate:
  enabled: false

ingress:
  enabled: false

extraInitContainers:
  - name: init-db
    image: ghcr.io/home-operations/postgres-init:17.5
    env:
      - name: INIT_POSTGRES_DBNAME
        value: open-webui
      - name: INIT_POSTGRES_HOST
        value: "db-rw.database.svc"
      - name: INIT_POSTGRES_USER
        value: ollama
      - name: INIT_POSTGRES_SUPER_PASS
        valueFrom:
          secretKeyRef:
            name: db-superuser
            key: password
      - name: INIT_POSTGRES_PASS
        valueFrom:
          secretKeyRef:
            name: ollama-db-creds
            key: POSTGRES_USER_PASSWORD

persistence:
  enabled: true
  size: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ceph-block-retain
  provider: local

# -- Service values to expose Open WebUI pods to cluster
service:
  type: ClusterIP
  port: 80
  containerPort: 8080

# -- Enables the use of OpenAI APIs
enableOpenaiApi: true

# hostAliases:
# - ip: "172.31.0.11"
#   hostnames:
#   - "keycloak.cloud.danmanners.com"

sso:
  enabled: false

extraResources:
  # Create the public Ollama Web UI service
  - apiVersion: v1
    kind: Service
    metadata:
      name: ollama-extname
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ollama.cloud.danmanners.com
        external-dns.alpha.kubernetes.io/ttl: "300"
    spec:
      type: ExternalName
      externalName: unifi-home.homelab.danmanners.com
  # Create the Gateway API HTTPRoute for the public Ollama Web UI service
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: aiml
      namespace: aiml
      annotations:
        external-dns.alpha.kubernetes.io/hostname: chat.capi-core.homelab.danmanners.com
        external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
        gatus.home-operations.com/enabled: "false"
    spec:
      hostnames:
        - chat.capi-core.homelab.danmanners.com
      parentRefs:
        - kind: Gateway
          group: gateway.networking.k8s.io
          name: gwapi
          namespace: default
          sectionName: https
      rules: &openwebui-rules
        - backendRefs:
            - group: ""
              kind: Service
              name: open-webui
              port: 80
              weight: 1
          matches:
            - path:
                type: PathPrefix
                value: /
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: aiml-cloud
      namespace: aiml
      annotations:
        external-dns.alpha.kubernetes.io/controller: "false"
        external-dns.alpha.kubernetes.io/hostname: ollama.cloud.danmanners.com
        external-dns.alpha.kubernetes.io/target: unifi-home.homelab.danmanners.com
        external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
        external-dns.alpha.kubernetes.io/ttl: "300"
        gatus.home-operations.com/enabled: "true"
        gatus.home-operations.com/endpoint: |-
          name: Open WebUI
          conditions:
            - "[STATUS] == 200"
          url: http://open-webui.aiml.svc.cluster.local/status
          method: GET
    spec:
      hostnames:
        - ollama.cloud.danmanners.com
      parentRefs:
        - kind: Gateway
          group: gateway.networking.k8s.io
          name: gwapi
          namespace: default
          sectionName: https-cloud
      rules: *openwebui-rules

extraEnvVars:
  - name: "POSTGRES_USER_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: ollama-db-creds
        key: POSTGRES_USER_PASSWORD
  - name: "POSTGRES_DB"
    value: "postgresql://ollama:$(POSTGRES_USER_PASSWORD)@db-rw.database.svc:5432/open-webui" #trufflehog:ignore
