nameOverride: ""
namespaceOverride: ""
ollama:
  enabled: true
  fullnameOverride: "open-webui-ollama"
  ollama:
    gpu:
      enabled: false
    models:
      pull:
      - llama3
      - qwen3
      run:
      - qwen3
  runtimeClassName: nvidia
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          # On discrete-GPU based systems NFD adds the following label where 10de is the NVIDIA PCI vendor ID
          - key: feature.node.kubernetes.io/pci-0300_10de.present
            operator: In
            values:
            - "true"
        - matchExpressions:
          # We allow a GPU deployment to be forced by setting the following label to "true"
          - key: "nvidia.com/gpu.present"
            operator: In
            values:
            - "true"
  persistentVolume:
    enabled: true
    size: 80Gi
    storageClass: ceph-rbd-retain
    accessModes:
    - ReadWriteOnce

pipelines:
  enabled: false

# -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
ollamaUrls: []

# -- Disables taking Ollama Urls from `ollamaUrls`  list
ollamaUrlsFromExtraEnv: false

# -- Value of cluster domain
clusterDomain: cluster.local

image:
  repository: ghcr.io/open-webui/open-webui
  tag: ""
  pullPolicy: "IfNotPresent"

serviceAccount:
  enable: true

copyAppData:
  resources: {}

managedCertificate:
  enabled: false

ingress:
  enabled: false

persistence:
  enabled: true
  size: 20Gi
  accessModes:
  - ReadWriteOnce
  storageClass: ceph-rbd-retain
  provider: local

# -- Service values to expose Open WebUI pods to cluster
service:
  type: ClusterIP
  port: 80
  containerPort: 8080

# -- Enables the use of OpenAI APIs
enableOpenaiApi: false

hostAliases:
- ip: "172.31.0.17"
  hostnames:
  - "keycloak.cloud.danmanners.com"

sso:
  enabled: true
  enableSignup: true
  mergeAccountsByEmail: true
  enableRoleManagement: false
  enableGroupManagement: true

  oidc:
    enabled: true
    clientId: aiml-open-webui
    clientExistingSecret: open-webui-oidc-secret
    clientExistingSecretKey: clientSecret
    providerUrl: https://keycloak.cloud.danmanners.com/realms/master/.well-known/openid-configuration
    providerName: "SSO"
    scopes: "openid email profile"

  roleManagement:
    rolesClaim: "roles"
    allowedRoles: ""
    adminRoles: ""

  groupManagement:
    groupsClaim: "groups"

  trustedHeader:
    enabled: false
    emailHeader: ""
    nameHeader: ""

# -- Extra resources to deploy with Open WebUI
extraResources: []

# -- Configure database URL, needed to work with Postgres (example: `postgresql://<user>:<password>@<service>:<port>/<database>`), leave empty to use the default sqlite database
databaseUrl: ""

# -- Postgresql configuration (see. https://artifacthub.io/packages/helm/bitnami/postgresql)
postgresql:
  enabled: false
  fullnameOverride: open-webui-postgres
  architecture: standalone
  auth:
    database: open-webui
    postgresPassword: 0p3n-w3bu!
    username: open-webui
    password: 0p3n-w3bu!
  primary:
    persistence:
      size: 1Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
