apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ceph-retain-sc.yaml

patches:
  - path: rbd-csi-snapshotter-patch.yaml
    target:
      kind: Deployment
      name: rook-ceph.rbd.csi.ceph.com-ctrlplugin
