apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph.rbd.csi.ceph.com-ctrlplugin
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v10.0.0
          args: ["--v=5","--csi-address=/csi/csi.sock"]
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
