apiVersion: batch/v1
kind: Job
metadata:
  name: patch-rbd-ctrlplugin-add-snapshotter
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/hook: PostSync,SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["kubectl"]
          args:
            - patch
            - deployment/rook-ceph.rbd.csi.ceph.com-ctrlplugin
            - "-n"
            - "rook-ceph"
            - "--type=json"
            - '-p=[{"op":"add","path":"/spec/template/spec/containers/-","value":{"name":"csi-snapshotter","image":"registry.k8s.io/sig-storage/csi-snapshotter:v10.0.0","args":["--v=5","--csi-address=/csi/csi.sock"],"volumeMounts":[{"name":"socket-dir","mountPath":"/csi"}]}}]'
      restartPolicy: Never
  backoffLimit: 2
