---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-secret
spec:
  secretStoreRef:
    name: openbao-labops
    kind: ClusterSecretStore
  target:
    name: hf-secret
    creationPolicy: Owner
  refreshInterval: 1h
  data:
    - secretKey: token
      remoteRef:
        key: dan/aiml/hf-secret
        property: token
