---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nvidia-llm-api-key
  namespace: aiml
spec:
  encryptedData:
    api-key: AgAWEuCBohPbhNi8xxzNs2TrMX59+yjSEVoADHxv0BIE3dYG/FbLk549FGltlPqT3JWP1d4M8pl73rdO1om0YXL/tiQP9OJdIU9wq2fWw+eKw3kiCPom5HlKUbwyy20/zIzD9zJV54Lt/lO3DDBlXWChQX/W8WdXL0/GGt58pjSQm6ON1mwRd0LPB0qcJKsDqy2N7LNaRoH6q2KnPJCws4o6rIJJMi0Ju/v8L3vTCm76MhrtAaNgYxTv7jzMiW5MQQgxvIEhzE0ZHw/iBsxB7rjsISJGA9Cws0KJfKRe49MsMH2vPLEHOpXvGbjxcqM/FFaG4Qo+pUtu9UGy13fTx0RiOhb1DXTvC80k8G61RM23SvsCexBxpaREFENdHJNG4sbvRvjmPzZyZWEE3j2Pt9ULwMVSojfzu0aFSmMoiS4ibK0Fr5xSvZipAluK73D5eFqIi3fPa/oeUt2vATq0uvtseaWGHx+jLjN/7cqFReX3GLkQ20i+vGd3M0R1uhEwRE/QSP/e3ipVa1pUGcuMBTMOi6SHKatZNdABAgT6jYJyEjwhR6+OTqbMO6hB2LAmjNWwiIZJ+y+iPwucXVs+GeWBwsHK+qGaJxN+kFXhSABbqsTV5Xg5FZ60+7vqjBDV6NSvX0GJ/GhCes04nN2RE+IEliTO8mfJ7nRNhFgmZjnWn0xlFzxLLXUCiFmud0zLWW/D3d2Tkk/5aDf6HA0SDUA1NAW3PBnBOdNeMgaa1Uqq8288JfCH3iFbO76gQb6k/AhM8QvBbTMBn0ZoD8M/kzOW
  template:
    metadata:
      name: nvidia-llm-api-key
      namespace: aiml
    type: Opaque
