---
defaultPodOptions:
  automountServiceAccountToken: true
  enableServiceLinks: false
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    initContainers:
      kubectl-setup:
        image:
          repository: docker.io/library/alpine
          tag: "3.22"
        command:
          - /bin/ash
          - -c
          - |
            apk add --no-cache kubectl
            token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            ca=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 -w0)
            export KUBECONFIG=/tmp/config
            kubectl config set-cluster default \
              --server=https://kubernetes.default.svc \
              --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
              --embed-certs=true
            kubectl config set-credentials default --token=${token}
            kubectl config set-context default --cluster default --user default
            kubectl config use-context default
            chown 1001:1001 /tmp/config
            cp /usr/bin/kubectl /tmp/kubectl
        env:
          - name: service_account
            value: k8s-mcp
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
    containers:
      mcp:
        image:
          # https://github.com/containers/kubernetes-mcp-server
          # repository: quay.io/manusa/kubernetes_mcp_server
          # tag: "latest"
          # https://github.com/reza-gholizade/k8s-mcp-server
          repository: docker.io/ginnux/k8s-mcp-server
          tag: "latest"
          pullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
          - name: mcp
            containerPort: 8080
            protocol: TCP
        args:
          - -mode
          - streamable-http
          - -port
          - "8080"
          - -read-only
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 1Gi
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      mcp:
        enabled: true
        port: 8080
        targetPort: mcp
        protocol: TCP

serviceAccount:
  k8s-mcp:
    enabled: true

persistence:
  kubeconfig:
    enabled: true
    type: emptyDir
    advancedMounts:
      main:
        mcp:
          - path: /home/appuser/.kube/
            mountPropagation: None
            readOnly: true
        kubectl-setup:
          - path: /tmp
            mountPropagation: None
            readOnly: false

rbac:
  roles:
    cluster-readonly:
      enabled: true
      type: ClusterRole
      rules:
        # Core API resources (v1)
        - apiGroups: [""]
          resources:
            - bindings
            - componentstatuses
            - configmaps
            - endpoints
            - events
            - limitranges
            - namespaces
            - nodes
            - persistentvolumeclaims
            - persistentvolumes
            - pods
            - podtemplates
            - replicationcontrollers
            - resourcequotas
            - serviceaccounts
            - services
          verbs: ["get", "list", "watch"]

        # ACME Cert-Manager resources
        - apiGroups: ["acme.cert-manager.io"]
          resources:
            - challenges
            - orders
          verbs: ["get", "list", "watch"]

        # GitHub Actions Runner Controller
        - apiGroups: ["actions.github.com"]
          resources:
            - autoscalinglisteners
            - autoscalingrunnersets
            - ephemeralrunners
            - ephemeralrunnersets
          verbs: ["get", "list", "watch"]

        # Admission Registration
        - apiGroups: ["admissionregistration.k8s.io"]
          resources:
            - mutatingadmissionpolicies
            - mutatingadmissionpolicybindings
            - mutatingwebhookconfigurations
            - validatingadmissionpolicies
            - validatingadmissionpolicybindings
            - validatingwebhookconfigurations
          verbs: ["get", "list", "watch"]

        # API Extensions
        - apiGroups: ["apiextensions.k8s.io"]
          resources:
            - customresourcedefinitions
          verbs: ["get", "list", "watch"]

        # API Registration
        - apiGroups: ["apiregistration.k8s.io"]
          resources:
            - apiservices
          verbs: ["get", "list", "watch"]

        # Apps
        - apiGroups: ["apps"]
          resources:
            - controllerrevisions
            - daemonsets
            - deployments
            - replicasets
            - statefulsets
          verbs: ["get", "list", "watch"]

        # ArgoCD
        - apiGroups: ["argoproj.io"]
          resources:
            - applications
            - applicationsets
            - appprojects
          verbs: ["get", "list", "watch"]

        # Authentication
        - apiGroups: ["authentication.k8s.io"]
          resources:
            - selfsubjectreviews
            - tokenreviews
          verbs: ["get", "list", "watch"]

        # Authorization
        - apiGroups: ["authorization.k8s.io"]
          resources:
            - localsubjectaccessreviews
            - selfsubjectaccessreviews
            - selfsubjectrulesreviews
            - subjectaccessreviews
          verbs: ["get", "list", "watch"]

        # Autoscaling
        - apiGroups: ["autoscaling"]
          resources:
            - horizontalpodautoscalers
          verbs: ["get", "list", "watch"]

        # Batch
        - apiGroups: ["batch"]
          resources:
            - cronjobs
            - jobs
          verbs: ["get", "list", "watch"]

        # Sealed Secrets
        - apiGroups: ["bitnami.com"]
          resources:
            - sealedsecrets
          verbs: ["get", "list", "watch"]

        # Custom PowerDNS Challenge
        - apiGroups: ["capi-core.homelab.danmanners.com"]
          resources:
            - pdns
          verbs: ["get", "list", "watch"]

        # Rook Ceph
        - apiGroups: ["ceph.rook.io"]
          resources:
            - cephblockpoolradosnamespaces
            - cephblockpools
            - cephbucketnotifications
            - cephbuckettopics
            - cephclients
            - cephclusters
            - cephcosidrivers
            - cephfilesystemmirrors
            - cephfilesystems
            - cephfilesystemsubvolumegroups
            - cephnfses
            - cephobjectrealms
            - cephobjectstores
            - cephobjectstoreusers
            - cephobjectzonegroups
            - cephobjectzones
            - cephrbdmirrors
          verbs: ["get", "list", "watch"]

        # Cert-Manager
        - apiGroups: ["cert-manager.io"]
          resources:
            - certificaterequests
            - certificates
            - clusterissuers
            - issuers
          verbs: ["get", "list", "watch"]

        # Certificate Signing Requests
        - apiGroups: ["certificates.k8s.io"]
          resources:
            - certificatesigningrequests
          verbs: ["get", "list", "watch"]

        # Cilium
        - apiGroups: ["cilium.io"]
          resources:
            - ciliumbgpadvertisements
            - ciliumbgpclusterconfigs
            - ciliumbgpnodeconfigoverrides
            - ciliumbgpnodeconfigs
            - ciliumbgppeerconfigs
            - ciliumbgppeeringpolicies
            - ciliumcidrgroups
            - ciliumclusterwideenvoyconfigs
            - ciliumclusterwidenetworkpolicies
            - ciliumendpoints
            - ciliumenvoyconfigs
            - ciliumexternalworkloads
            - ciliumidentities
            - ciliuml2announcementpolicies
            - ciliumloadbalancerippools
            - ciliumlocalredirectpolicies
            - ciliumnetworkpolicies
            - ciliumnodeconfigs
            - ciliumnodes
            - ciliumpodippools
          verbs: ["get", "list", "watch"]

        # Coordination
        - apiGroups: ["coordination.k8s.io"]
          resources:
            - leases
          verbs: ["get", "list", "watch"]

        # Discovery
        - apiGroups: ["discovery.k8s.io"]
          resources:
            - endpointslices
          verbs: ["get", "list", "watch"]

        # Events
        - apiGroups: ["events.k8s.io"]
          resources:
            - events
          verbs: ["get", "list", "watch"]

        # Istio Extensions
        - apiGroups: ["extensions.istio.io"]
          resources:
            - wasmplugins
          verbs: ["get", "list", "watch"]

        # External DNS
        - apiGroups: ["externaldns.k8s.io"]
          resources:
            - dnsendpoints
          verbs: ["get", "list", "watch"]

        # Flow Control
        - apiGroups: ["flowcontrol.apiserver.k8s.io"]
          resources:
            - flowschemas
            - prioritylevelconfigurations
          verbs: ["get", "list", "watch"]

        # Gateway API
        - apiGroups: ["gateway.networking.k8s.io"]
          resources:
            - backendtlspolicies
            - gatewayclasses
            - gateways
            - grpcroutes
            - httproutes
            - referencegrants
            - tcproutes
            - tlsroutes
            - udproutes
          verbs: ["get", "list", "watch"]

        # Gateway API Extensions
        - apiGroups: ["gateway.networking.x-k8s.io"]
          resources:
            - xbackendtrafficpolicies
            - xlistenersets
          verbs: ["get", "list", "watch"]

        # Metrics
        - apiGroups: ["metrics.k8s.io"]
          resources:
            - nodes
            - pods
          verbs: ["get", "list", "watch"]

        # Istio Networking
        - apiGroups: ["networking.istio.io"]
          resources:
            - destinationrules
            - envoyfilters
            - gateways
            - proxyconfigs
            - serviceentries
            - sidecars
            - virtualservices
            - workloadentries
            - workloadgroups
          verbs: ["get", "list", "watch"]

        # Networking
        - apiGroups: ["networking.k8s.io"]
          resources:
            - ingressclasses
            - ingresses
            - ipaddresses
            - networkpolicies
            - servicecidrs
          verbs: ["get", "list", "watch"]

        # Node Feature Discovery
        - apiGroups: ["nfd.k8s-sigs.io"]
          resources:
            - nodefeaturerules
            - nodefeatures
          verbs: ["get", "list", "watch"]

        # Node Runtime Classes
        - apiGroups: ["node.k8s.io"]
          resources:
            - runtimeclasses
          verbs: ["get", "list", "watch"]

        # Object Bucket
        - apiGroups: ["objectbucket.io"]
          resources:
            - objectbucketclaims
            - objectbuckets
          verbs: ["get", "list", "watch"]

        # Policy
        - apiGroups: ["policy"]
          resources:
            - poddisruptionbudgets
          verbs: ["get", "list", "watch"]

        # Cloud Native PostgreSQL
        - apiGroups: ["postgresql.cnpg.io"]
          resources:
            - backups
            - clusterimagecatalogs
            - clusters
            - databases
            - imagecatalogs
            - poolers
            - publications
            - scheduledbackups
            - subscriptions
          verbs: ["get", "list", "watch"]

        # RBAC
        - apiGroups: ["rbac.authorization.k8s.io"]
          resources:
            - clusterrolebindings
            - clusterroles
            - rolebindings
            - roles
          verbs: ["get", "list", "watch"]

        # Scheduling
        - apiGroups: ["scheduling.k8s.io"]
          resources:
            - priorityclasses
          verbs: ["get", "list", "watch"]

        # Istio Security
        - apiGroups: ["security.istio.io"]
          resources:
            - authorizationpolicies
            - peerauthentications
            - requestauthentications
          verbs: ["get", "list", "watch"]

        # Storage
        - apiGroups: ["storage.k8s.io"]
          resources:
            - csidrivers
            - csinodes
            - csistoragecapacities
            - storageclasses
            - volumeattachments
          verbs: ["get", "list", "watch"]

        # Istio Telemetry
        - apiGroups: ["telemetry.istio.io"]
          resources:
            - telemetries
          verbs: ["get", "list", "watch"]

        # Secrets (separate rule for different verbs)
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["list"]
  bindings:
    cluster-readonly:
      enabled: true
      type: ClusterRoleBinding
      roleRef:
        kind: ClusterRole
        name: k8s-mcp
        apiGroup: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: k8s-mcp
          namespace: aiml
