customization:
  extraKernelArgs:
    - apparmor=0
    - init_on_alloc=0
    - init_on_free=0
    - mitigations=off
    - security=none
    - selinux=0
    - talos.auditd.disabled=1
  systemExtensions:
    officialExtensions:
      - siderolabs/amd-ucode
      - siderolabs/binfmt-misc
      - siderolabs/nvme-cli
      - siderolabs/util-linux-tools
      - siderolabs/wasmedge
