---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: nvidia-llama
  namespace: aiml
spec:
  modelName: nvidia-llama
  params:
    model: openai/nvidia-qwen3-32b-nvfp4
    apiBase: http://nvidia-vllm-core.aiml.svc.cluster.local:8080/v1
    apiKeyRef:
      name: nvidia-llm-api-key
      key: api-key
    additional:
      input_cost_per_token: 0.0000023860
      output_cost_per_token: 0.0000028322
  info:
    maxInputTokens: 262144
    supportsFunctionCalling: true
    supportsVision: false
