---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: intel-llama
  namespace: aiml
spec:
  modelName: intel-llama
  params:
    model: openai/intel-ministral-8b-fp8
    apiBase: http://intel-vllm-core.aiml.svc.cluster.local:8080/v1
    apiKeyRef:
      name: intel-llm-api-key
      key: api-key
    additional:
      input_cost_per_token: 0.00000249
      output_cost_per_token: 0.00000249
  info:
    maxInputTokens: 32768
