---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: gptoss-llama
  namespace: aiml
spec:
  modelName: gptoss-llama
  params:
    model: openai/gpt-oss-20b-f16
    apiBase: http://10.3.0.27:8080/v1
    apiKeyRef:
      name: gptoss-llm-api-key
      key: api-key
  info:
    maxInputTokens: 131072
