---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observability-m2m
  namespace: monitoring
spec:
  secretStoreRef:
    name: openbao-labops
    kind: ClusterSecretStore
  target:
    name: observability-m2m
    creationPolicy: Owner
  refreshInterval: 1h
  data:
    - secretKey: client_id
      remoteRef:
        key: dan/monitoring/observability-m2m
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: dan/monitoring/observability-m2m
        property: client_secret
