---
defaultPodOptions:
  automountServiceAccountToken: true
  enableServiceLinks: true
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    containers:
      core:
        ports:
        - name: http
          containerPort: &port 5678
          protocol: TCP
        image:
          repository: docker.n8n.io/n8nio/n8n
          tag: "1.99.1"
          pullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: true
        env:
        - name: N8N_HOST
          value: n8n.cloud.danmanners.com
        - name: N8N_PORT
          value: *port
        - name: N8N_PROTOCOL
          value: http
        - name: NODE_ENV
          value: production
        - name: N8N_TRUST_PROXY
          value: true
        - name: N8N_SECURE_COOKIE
          value: false
        - name: WEBHOOK_URL
          value: https://n8n.cloud.danmanners.com
        - name: GENERIC_TIMEZONE
          value: America/New_York
        - name: N8N_RUNNERS_ENABLED
          value: true
        - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
          value: false
        - name: NODE_FUNCTION_ALLOW_BUILTIN
          value: "*"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: dgram
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      api:
        enabled: true
        port: *port
        targetPort: http
        protocol: TCP
  extname:
    enabled: true
    primary: false
    controller: main
    type: ExternalName
    externalName: unifi-home.homelab.danmanners.com
    annotations:
      external-dns.alpha.kubernetes.io/hostname: n8n.cloud.danmanners.com
      external-dns.alpha.kubernetes.io/ttl: "300"

route:
  core:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/controller: "false"
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gwapi
      namespace: default
      sectionName: https-cloud
    hostnames:
    - n8n.cloud.danmanners.com
    rules:
    - backendRefs:
      - name: n8n-core
        port: *port
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
      timeouts:
        backendRequest: 0s
        request: 0s

persistence:
  home:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-rbd-retain
    accessMode: ReadWriteOnce
    size: 60Gi
    retain: true
    globalMounts:
    - path: /home/node/.n8n
      readOnly: false
  files:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-rbd-retain
    accessMode: ReadWriteOnce
    size: 60Gi
    retain: true
    globalMounts:
    - path: /files
      readOnly: false
