---
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  runtimeClassName: nvidia
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    containers:
      core:
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        image:
          repository: ghcr.io/docling-project/docling-serve-cu124
          tag: "v0.16.0"
          pullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: DOCLING_SERVE_ENABLE_UI
          value: "true"
        resources:
          limits:
            cpu: 1
            memory: 4Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 250m
            memory: 1Gi
            nvidia.com/gpu: "1"
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 5001
        targetPort: http
        protocol: TCP

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-rbd-retain
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true
    globalMounts:
    - path: /modelcache
      readOnly: false
