crds:
  enabled: true

cleanPrometheusOperatorObjectNames: true

grafana:
  envFrom:
    - GF_AUTH_GENERIC_OAUTH_API_URL: https://keycloak.cloud.danmanners.com/api/oidc/userinfo
    - GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://keycloak.cloud.danmanners.com/api/oidc/authorization
    - GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
    - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: https://keycloak.cloud.danmanners.com/api/oidc/token
    - GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
    - GF_EXPLORE_ENABLED: true
    - GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel,yesoreyeram-infinity-datasource
    - GF_SECURITY_ANGULAR_SUPPORT_ENABLED: true
    - GF_SECURITY_COOKIE_SAMESITE: grafana
    - GF_SERVER_ROOT_URL: https://grafana.${SECRET_PUBLIC_DOMAIN}
    - GF_SECURITY_HIDE_VERSION: true

prometheus:
  prometheusSpec:
    retention: 14d
    retentionSize: 60Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block-retain
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 64Gi
