---
defaultPodOptions:
  automountServiceAccountToken: true
  enableServiceLinks: true
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    containers:
      core:
        ports:
          - name: ws
            containerPort: &port 3000
            protocol: TCP
        image:
          repository: mcr.microsoft.com/playwright
          tag: "v1.49.1-noble"
          pullPolicy: "IfNotPresent"
        command:
          - "/bin/sh"
        args:
          - "-c"
          - |
            npx -y playwright@1.49.1 \
            run-server \
            --port 3000 \
            --host 0.0.0.0
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      api:
        enabled: true
        port: *port
        targetPort: ws
        protocol: TCP
