---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-user
  namespace: octopus
spec:
  encryptedData:
    password: AgAB45nuT6edJFNwdHquv+MciP6qfuTj7QYOJcPTWN3VIWyM5QT3F3zUdc6XePSxJbIc1mnlZXXZZDe/vF8oQGmboGSsbZlV75vLwLwt5id3LY8yFJSyDN4U2GD2N1c16et1FUKlFYZ8bT8OxA2jn8UtUyE6I6gjoev+RcgpPO3C91ySIjFRZpBBIwP/aJMBvtkwJAYJboQRHPbmDHwlfNcXSqYNtX9VTZS45Sf9HWCfSf1rJLDguAnaUQeMTHOvEw3zaunPqVUVOrFVabsUpfSQu89Z8z2YC1yfRp5Ekv39nWGQOOyGRq7YSqmsPNTjyUSlNfejTRTLzTfFKVrnnFdm9q1bcfk30nDKVUf0DqtB2VEWS9E5pc9ZH9i76bALdQ6uf6cP5azW2s9KxB6xPSW20p6BzeSuwYG+zctMzCEB48W5hKTsGxAWH2Hp0jrJ2Us3k6e7jRXm+KUHj7LLjWRA7P5bDQREyJ53O2E2vLib5BrNzxUoSb4z3u04LYlyfxhcleiKjmYNHzERPleW3hEunx/ZzY8ycMweWbKc6oZerjQOWQVjNFp5H+8Mxf4g6G5DvIxypXvFSBL1ZTwEKlYa+MPEQCWmiY9HslZPkAyoTbLs7YkYEE+MH50W9+UGfU/SxLWa18TkDjWjy19IUOTNeDIZOXTryicdEyNQMh5isqiLldgGRpCc38EVGrMRMLQ6wyt/Ce4buK415Bl+Qg7bVKRb
    username: AgAI6eVUVWok8yy5Ps/AlpnrE/jrCewuK53kI8HLWFk69YdtrLsXTguuRPXTJCNHD6rkxxrFGXyajQUiMcqH77BRxb4PWH5IowpV4xC5/kU2PhtQ9e76vlhoSwaQNZKpa+wDp7FAnkYTfgQfk9FzeszFLI/glDpPKFR8ld5C4EimoQOjDraSFDpwIW95V7yffqMnPVdyDrHDuFySKlnkcOREm4Z1Z5cvzeGlal+ZnBIcHLfUWNOX4Iyz51O5CQjGYbuuVp8C/Gl76ZJ8W1E1VuJd/KouIT4nFZPtZ4drK//JS58ytZPqDNu5pYcaGxD4gOFwo3WZgjZgVhXO0YW/Z2TS3yWnORaQRTBEbSTW55sQRO9WMzhX+/WXkgWOhnF9CvulII2iAWkxXgMPumPQGcef3ibv+P7QktbSAzepoe4a/tiTJuQCcpqii7PsTeGhE9jSlOcGMaujMWpPqumekTIK4rUQUQ3Jw/oXGHPyrzJdyREcrYZSRV3OVzuQYYMTev2Uw+KvjL+mEk4Mqt8k0EJ1vcqKqNBDMv82HFLKul1lPg9P19YzqwJr5X0Zeu929fax1Ay2q7nyxGmzk6Kr61M9sXe9ZuiX2kXG/73ywR8tD3Msnh3ru63uEoSiaYmJHaQlSifC0RB8pLsmLmUWMTC3pb2VTYEgqF7eRE7/9Ikx0N2dKsTWmAR8uKefvLMhRVDO+mgjes32Y42vDXRP
  template:
    metadata:
      name: admin-user
      namespace: octopus
    type: Opaque
