apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-cert
  namespace: keycloak
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-dns01
spec:
  secretName: keycloak-tls-cert
  duration: 1128h # 47 days
  renewBefore: 168h # 7 days
  commonName: keycloak.capi-core.homelab.danmanners.com
  dnsNames:
  - keycloak.capi-core.homelab.danmanners.com
  - keycloak.cloud.danmanners.com
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
  - server auth
  - client auth
