apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-core
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command:
        - sh
        - -c
        - |
          until nc -z $(DB_HOST) 5432; do
          echo "Waiting for database to be ready..."
          sleep 5
          done
          echo "Database is ready!"
        env:
        - name: DB_HOST
          value: keycloak-rw.keycloak.svc.cluster.local
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.2
        args:
        - start
        - --http-port=8080
        - --http-enabled=true
        - --https-port=8443
        - --https-certificate-file=/etc/x509/https/tls.crt
        - --https-certificate-key-file=/etc/x509/https/tls.key
        - --db-url-host=$(DB_HOST)
        - --hostname-strict=false
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/x509/https
          readOnly: true
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: DB_HOST
          value: keycloak-rw.keycloak.svc.cluster.local
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-superuser-secret
              key: password
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-superuser-secret
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-superuser-secret
              key: password
        - name: KC_DB_URL_DATABASE
          value: app
        readinessProbe:
          httpGet:
            path: /admin/master/console/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
      volumes:
      - name: tls-certs
        secret:
          secretName: keycloak-core-internal-tls
