---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: keycloak-tls-policy
  namespace: keycloak
spec:
  targetRefs:
  - name: keycloak-core
    kind: Service
    group: ""
    sectionName: https
  validation:
    hostname: keycloak-core.keycloak.svc.cluster.local
    caCertificateRefs:
    - name: keycloak-core-internal-tls
      kind: Secret
      group: ""
