---
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Always
  runtimeClassName: nvidia
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    containers:
      core:
        ports:
        - name: http
          containerPort: &port 8188
          protocol: TCP
        image:
          repository: harbor.cloud.danmanners.com/library/danmanners/comfyui
          tag: v0.3.45
          pullPolicy: Always
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        - name: CLI_ARGS
          value: "--verbose=DEBUG"
        resources:
          limits:
            cpu: 1
            memory: 6Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 250m
            memory: 1Gi
            nvidia.com/gpu: "1"
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: *port
        targetPort: http
        protocol: TCP

persistence:
  home:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-rbd-retain
    accessMode: ReadWriteOnce
    size: 200Gi
    retain: true
    globalMounts:
    - path: /app/ComfyUI/models/
      readOnly: false
