---
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Always
  runtimeClassName: nvidia
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 2
    initContainers:
      prep-models-dir:
        image:
          repository: &repo harbor.cloud.danmanners.com/library/danmanners/comfyui
          tag: &tag v0.3.49
        command:
          - /bin/sh
          - -c
          - |
            mkdir -p /app/ComfyUI/models/checkpoints \
            /app/ComfyUI/models/clip \
            /app/ComfyUI/models/clip_vision \
            /app/ComfyUI/models/configs \
            /app/ComfyUI/models/controlnet \
            /app/ComfyUI/models/diffusers \
            /app/ComfyUI/models/diffusion_models \
            /app/ComfyUI/models/embeddings \
            /app/ComfyUI/models/gligen \
            /app/ComfyUI/models/hypernetworks \
            /app/ComfyUI/models/loras \
            /app/ComfyUI/models/photomaker \
            /app/ComfyUI/models/style_models \
            /app/ComfyUI/models/text_encoders \
            /app/ComfyUI/models/unet \
            /app/ComfyUI/models/upscale_models \
            /app/ComfyUI/models/vae \
            /app/ComfyUI/models/vae_approx
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "256Mi"
    containers:
      browser:
        image:
          repository: harbor.cloud.danmanners.com/library/gtsteffaniak/filebrowser
          tag: 0.8.5-beta-slim
        ports:
          - name: browser
            containerPort: 80
            protocol: TCP
        env:
          - name: FILEBROWSER_CONFIG
            value: /home/filebrowser/data/config.yaml
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "100m"
            memory: "96Mi"
          limits:
            cpu: "2000m"
            memory: "800Mi"
      core:
        ports:
          - name: http
            containerPort: &port 8188
            protocol: TCP
        image:
          repository: *repo
          tag: *tag
          pullPolicy: Always
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
          - name: CLI_ARGS
            value: "--verbose=DEBUG"
        resources:
          limits:
            cpu: 6
            memory: 40Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 250m
            memory: 1Gi
            nvidia.com/gpu: "1"
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

configMaps:
  browser:
    enabled: true
    data:
      config.yaml: |
        server:
          port: 80
          baseURL:  "/"
          logging:
            - levels: "info|warning|error|debug"
          sources:
            - path: /app/ComfyUI/output
              name: ComfyUI Output
            - path: /app/ComfyUI/models
              name: ComfyUI Models
        userDefaults:
          preview:
            image: true
            popup: true
            video: false
            office: false
            highQuality: false
          darkMode: true
          disableSettings: false
          singleClick: false
          permissions:
            admin: false
            modify: false
            share: false
            api: false

service:
  main:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: *port
        targetPort: http
        protocol: TCP
      browser:
        enabled: true
        port: 8080
        targetPort: browser
        protocol: TCP
  lb:
    enabled: true
    controller: main
    primary: false
    type: LoadBalancer
    ports:
      http:
        enabled: true
        port: 80
        targetPort: http
        protocol: TCP
      browser:
        enabled: true
        port: 8080
        targetPort: browser
        protocol: TCP

persistence:
  models:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block-retain
    accessMode: ReadWriteOnce
    size: 300Gi
    retain: true
    globalMounts:
      - path: /app/ComfyUI/models/
        readOnly: false
  output:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block-retain
    accessMode: ReadWriteOnce
    size: 40Gi
    retain: true
    globalMounts:
      - path: /app/ComfyUI/output/
        readOnly: false
  workflows:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block-retain
    accessMode: ReadWriteOnce
    size: 4Gi
    retain: true
    globalMounts:
      - path: /app/ComfyUI/user/default/workflows/
        readOnly: false
  custom-nodes:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block-retain
    accessMode: ReadWriteOnce
    size: 4Gi
    retain: true
    globalMounts:
      - path: /app/ComfyUI/custom_nodes/
        readOnly: false
  browser:
    type: configMap
    name: comfyui
    defaultMode: 0644
    advancedMounts:
      main:
        browser:
          - path: /home/filebrowser/data/config.yaml
            mountPropagation: None
            readOnly: false
            subPath: config.yaml
