---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gptoss-llm-api-key
  namespace: aiml
spec:
  secretStoreRef:
    name: openbao-labops
    kind: ClusterSecretStore
  target:
    name: gptoss-llm-api-key
    creationPolicy: Owner
  refreshInterval: 1h
  data:
    - secretKey: api-key
      remoteRef:
        key: dan/aiml/bonsai-llm-api-key
        property: api-key
