apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aiml

resources:
  - serviceaccount.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - proxy.yaml
  - model-nvidia.yaml
  - model-intel.yaml
  - servicemonitor.yaml
  - httproute.yaml
  - external-name.yaml
