apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aiml

resources:
  - secret.litellm-master-key.yaml
  - proxy.yaml
  - model-nvidia.yaml
  - model-intel.yaml
  - servicemonitor.yaml
