---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: intel-llama
  namespace: aiml
spec:
  modelName: intel-llama
  params:
    model: openai/local
    apiBase: http://intel-vllm-core.aiml.svc.cluster.local:8080/v1
    apiKeyRef:
      name: intel-llm-api-key
      key: api-key
  info:
    maxInputTokens: 131072
