---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: bonsai-llama
  namespace: aiml
spec:
  modelName: bonsai-llama
  params:
    model: openai/ternary-bonsai-2-27B
    apiBase: http://10.2.30.217:8080/v1
  info:
    maxInputTokens: 65536
