---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-litellm
spec:
  provider:
    vault:
      server: https://keeper.goodmanners.services
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-labops
          role: eso-litellm
          serviceAccountRef:
            name: vault-litellm-reader
