---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMTeam
metadata:
  name: scum
  namespace: aiml
spec:
  proxyRef: router
  teamID: scum
  alias: scum
  models:
    - openai/gpt-oss-20b-f16
    - intel-llama
    - openai/nvidia-qwen3.8-turbo
  members:
    - userID: dan
      role: user
    - userID: james
      role: user
    - userID: coolguy1771
      role: admin
