---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capmox-manager-credentials
  namespace: capmox-system
spec:
  encryptedData:
    secret: AgANipONO48GxsjNjxNwpGD4STd8+v9WSLQL+dq+R55kT+6LG58JnIdKkeXo2Tq7fZCLwcyDjx5LBsAaaKsHPpHO0mgJcg9ptsPYhXtFtnrh4npp72wUoNZCpqOyajPz4xNIbEanf2PJIjc56SI5O8Il1YUm5DOAAyGL+Rbj0oPqrWtuQ4bYTutTIhai347EqXvfdXrneZkZotmkLdCycXOXQISFiKk2Bo54UkOanK4DCm4TKQtApZO+6DefD/gL2/sRuJEM4TUHooTxbCcCEPBmFNPqPtlOR0U41YL8+ykytVYTifxpbM9xI8nKbGDIdsO7EWCM9QNx1LJn7gGyyhr9bHRWa/e8NWkkS/dre/3VcidF6fK6zmxaIgx5DclAR/cF1P2RRXlKvH1rZyQaT6K2xN7UxjuVZhEH+C7ZAOdb0BjLrbXFYD+7yl2hYrupUGspWURTJn5ASp8dZY35TOcEqmoxJLhGBsczBeStWi+MPaift8xcjodI+6NSDFkZRgf0uqzZ+UaxTbdq5oeXHjMaSl0DRGcR72j5HoyCKN+9wT+9E/Qmf636aTnshmr+s6rwwRFBRoHkEjW5Oj5s52EMtxAn8sIUxXwoEQhxZZaaM3Uq8fQMiWTS3HRuem480Jvqa5FZCUPDdupgLfYGczEIiWxiEeDygK2DFrqGYDU8xZvQgi2VFGET3L9koQThoiG5l6jC5+UUBVdSLQ28UjjAVs3B59wqI666ao5K7p7XVhU7HFM=
    token: AgApPCZFxY6bZZznQJ2ZdeCEodw1U1DpABjv9WP66Qh/EDHEOjoL0YBufSjy1ILumk0poF90omzNhKhAI2ieDjj/Daj3BkSDLMnfGDVugkCb/IZk5nCZnBLhkVnJpAlBWcUSf1aen3P0kcBlIRWZOK27M5XEs+npseD1mKq4ThMlvJMspd7j1uOdiHyd7dkt/S+Pii12fDbNGiUMbVi+w/dLxJEy9lqgvAOB+NYVde2NzQGY54hiiVGrv1P2qeNpOyIrt/6b2O2baXun+aBGcKY0U02ocWpGoezRmKlPYkaofF1SWk2CzQb2KGsOFb+tukKsBtdDW7YQnJAq4jMPzCoLklDkfA/CyK57J0W+FpBMEprQhN2+Aaiwsi9eeh1KnscPF3YS8NP8G3Bn4qPIuBi09/EtMxNCPSnuxTd4z5G1yg6ydZ09/LeckkCPO8Kvwc6pLUaW8euVy3qLlysFKelHjW0EQNXKJJMwjvgSSduNmXO3XvmKnjl6fFJzDQWVSyFV3w/+ILLXuxMCKArKb+GvBrszuIk5I2v9Yqn9/qIUvugetpIAXwKa2tuJfI9bedRE1CZEKYzBF2Fb4vJRgIKIHort0U+dI1cfzsLkKCtT4p3oqX4EfBOZ2tBvPZrd2KHxdTCcANHzx4QeyP84qHg3CNTbiVJLu4w7pz1ovmw2qzY1H3b1sNkW9lSnRPmKN3EZSD14gX0JvXqFTeq1
    url: AgB8xxkHFxfRrNlJHq4VCliiQ4sQjZxTbgSBTUPLTr1z8VeVIfTcr7x0hqQT4sTIXTASzUFHEptG4dHobbDQQzw9UnZ6qmx5bkWMreOh8Gswm8x4+V9I8AJsJilwA7Hg0Fk7tKFVxClkzVUyDtlPoJq9WlbsRwN0ExdkN8RfcE+adJScROVGbmc0m8fUBPcFdJlG8giTPhhMdyo8C4WflUHlEN5mcqz+qIP1IYpkwI6quYFOOwAqpRV4vbOTrcBoiS495bQ4l981fb7gRGQ/9HX4q08H2vlIavYxsUpxQxryxTbL+UfXDupCntL5Zz/qaFvo3N5EPjbZlU3ktDM6b5FJXjRuj8VOobe2LQS+N0jWtOvOg1ou8zZGSP8SLGZp7i0HrHCwRir1t8XkgzvgA35/B/Gt4mTzpp44RdgNNtVrwswHuy/Wtur9Ulufw6w98bh8wyX38+Z37N8ukgpApd3OXAx+YdUrq5KT6CnLh7gPUrkYzNcsVmqs3i37ESeUJ2bXxcR/dUJkqkGg1EjLKMn/ClBncYgPUO33wjGegYCIkSWA6e89jnf6b+POXcuPzVOeSgFesG9T+HCUaYYuoSzU+Gs9cifeWSsiPcXEZCxeIHIVjtfKYmlEnQG4yft76rzc9ZWBrlMxuP5uu11YeoAoYwOYeBaPJtpMOmuMxpsIYo7QhZ+GuCUp2Zq+Nrg0crQxeJVrmezU8HGONRsryRvTz41w24yCFw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: infrastructure-proxmox
        clusterctl.cluster.x-k8s.io: ""
        platform.ionos.com/secret-type: proxmox-credentials
      name: capmox-manager-credentials
      namespace: capmox-system
    type: Opaque
