---
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    type: statefulset
    replicas: 1
    # strategy: Recreate
    revisionHistoryLimit: 2
    containers:
      core:
        ports:
        - name: server
          containerPort: 8211
          protocol: UDP
        - name: api
          containerPort: 8212
          protocol: TCP
        - name: steam
          containerPort: 27015
          protocol: UDP
        image:
          repository: thijsvanloef/palworld-server-docker
          tag: "dev"
          pullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: PORT
          value: "8211"
        - name: PLAYERS
          value: "16"
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: SERVER_PASSWORD
        - name: MULTITHREADING
          value: "true"
        - name: RCON_ENABLED
          value: "true"
        - name: RCON_PORT
          value: "25575"
        - name: TZ
          value: "UTC"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: ADMIN_PASSWORD
        - name: COMMUNITY
          value: "false"
        - name: SERVER_NAME
          value: "Femboy Island"
        - name: SERVER_DESCRIPTION
          value: "This one will probably stay online!"
        - name: CROSSPLAY_PLATFORMS
          value: "(Steam,Xbox,PS5,Mac)"
        resources:
          limits:
            cpu: 15000m
            memory: 28Gi
          requests:
            cpu: 8000m
            memory: 16Gi
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

service:
  core:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      api:
        enabled: true
        port: 8212
        targetPort: http
        protocol: TCP
      server:
        enabled: true
        port: 8211
        targetPort: server
        protocol: UDP
      steam:
        enabled: true
        port: 27015
        targetPort: steam
        protocol: UDP
  lb:
    enabled: true
    controller: main
    primary: true
    type: LoadBalancer
    ports:
      server:
        enabled: true
        port: 8211
        targetPort: server
        protocol: UDP
      steam:
        enabled: true
        port: 27015
        targetPort: steam
        protocol: UDP
  extname:
    enabled: true
    primary: false
    controller: main
    type: ExternalName
    externalName: unifi-home.homelab.danmanners.com
    annotations:
      external-dns.alpha.kubernetes.io/hostname: palworld.cloud.danmanners.com
      external-dns.alpha.kubernetes.io/ttl: "300"

route:
  core:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/controller: "false"
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gwapi
      namespace: default
      sectionName: https-cloud
    hostnames:
    - palworld.cloud.danmanners.com
    rules:
    - backendRefs:
      - name: palworld-core
        port: 8212
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
      timeouts:
        backendRequest: 0s
        request: 0s
  server:
    enabled: true
    kind: UDPRoute
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gwapi
      namespace: default
      sectionName: palworld-server
    rules:
    - backendRefs:
      - name: palworld-core
        port: 8211
        weight: 1
  steam:
    enabled: true
    kind: UDPRoute
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gwapi
      namespace: default
      sectionName: palworld-steam
    rules:
    - backendRefs:
      - name: palworld-core
        port: 27015
        weight: 1

rawResources:
  palworld:
    enabled: true
    apiVersion: cert-manager.io/v1
    kind: Certificate
    spec:
      spec:
        secretName: palworld-tls-cert
        duration: 1128h # 47 days
        renewBefore: 168h # 7 days
        dnsNames:
        - palworld.cloud.danmanners.com
        issuerRef:
          name: letsencrypt-dns01
          kind: ClusterIssuer
          group: cert-manager.io
        usages:
        - server auth
        - client auth

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-rbd-retain
    accessMode: ReadWriteOnce
    size: 40Gi
    retain: true
    globalMounts:
    - path: /palworld
      readOnly: false
