apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4-minimal-bookworm
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: ceph-rbd
  superuserSecret:
    name: keycloak-superuser-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  resources:
    requests:
      memory: "2Gi"
      cpu: "200m"
    limits:
      memory: "4Gi"
