name: opencode

on:
  issue_comment:
    types: [created]

jobs:
  opencode:
    runs-on: ubuntu-latest

    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /opencode') ||
      startsWith(github.event.comment.body, '/opencode')

    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run opencode
        uses: sst/opencode/github@latest
        env:
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
        with:
          model: "qwen3:4b"