---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artifact-keeper-dependency-track-credentials
  namespace: artifact-keeper
spec:
  encryptedData:
    admin-password: AgDFTm6wyqadXh97HTGsULMM/HaUgrXdpPami3LgTHYQ47n4XOS0godxsNQCNpxI14WOBqZuaeN5RPhWJxMHa9QetBcUD9j9/zOq2HOu8sxoA2QVhdEkhl8bGS67W3KRGmMAMapnCIStfqbgXrrM2OagCUl4fMCsuJn/tCl/u8ZEs8DHgXuByqyjNTWRkEnJiVybvQlvIK0IQm4jvEgsIVBIbSJiWmxHwZpmQthqtJ3VM/N00xkB8w9rz6nSKeI6mgI90vZzuv5/K2dGgPu7ziYK06PUKEwBA5v0zEI3JmCLM39IrY8663V7cjQYLiYFMcG1rW/EGrux4/LqmQpPGyJNl3XMvyuYuxVu2Z1q61sgpwPgisYn4JK75NbR9e/A6/sl0nkqnWXEwPZxiAohG2l39AqsPMKYLBmcSPtZfBu0T1HFO8TnrwneCK2PuPsBg5QUkpiJNNEPmVqDfcy7J3TZtkvXXciB7AnxkbekH4Icfhy7qxroWotqtZzCjHqK3oOghKLnIK/vtZh12FLMP8NbCgVNq7T4j64KLsc+Goz4v14Ayju7l30NSHQ1JeqPVrVe0uTyfSr2qWXgEE7+fTOkyxMX27CLMfLd8a0SbSx88SFAQn6A7KrGx3CIylldX5N9E6Xn3ki0zpB8gbVmkEKkg+HUEi2nMUqMnuAAnWjqbE0GfCErp49B+ygVOG4f61jFKOTTn/fxZVDJoqF3GmPnltEJAuHAVg6pntwBpaPWsw==
  template:
    metadata:
      name: artifact-keeper-dependency-track-credentials
      namespace: artifact-keeper
    type: Opaque
