---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artifact-keeper-jwt-secret
  namespace: artifact-keeper
spec:
  encryptedData:
    jwt-secret: AgBBB3mU+Bh6x2PVapoCq6bAWB6IxVWVpX4qZyHKS5VxhNnqUO4GhNkSCCjXIj8vFhFECnWnT0donaWKL1/lYvfBsS6xm24g6okpehH9UX74rm4aX2Jcn11Rv2eEjQT8mmLSXWAIyeimhWbf6uNUJXU9MzVXHh64PTISV6O12WamHTXRGJvVBosxRHIUvrDfSe+ME/SYXkG81zkuliW0mQZ4EZDGAusn4tLo61VnoFAGp8BbPAgs6U+JWh+Z+u0npSk2rXrdjVs1CoOWeuzCNOsfL73YrNA0eATZsMnhepKBp3oyGDoWLc/6zEw1LBVxTVDnPtNBMSaaLSUTtzyWGNAdgsE+YoUDS9o6OriXL48tRZlXJG/E+ku4prGA+o0/VWVKSu+/2g8mfBcHTVQd3D7dPTXeiZFinQY86b+f6/Em/mjWsSXmeByjSKbztELFXCmxPq/pStr5GNCYziA8kBaGzhpS4GzAs29FFr12uy/d6tel8XWRnzLkMH850Iu85vnLSopyrC2SQC3faCvpiHq8oWTdkiWBOnP9kXFyooxtgvQWg37lNIdNftbcnJ2gpycLFK7J7KAfPsV62J4nXfoOehynqMzzbnQL/zEsynFGzbPbDeJPro9jkPtUtICa+WJDrBOqv7yNX0/Cj8ESDvmEw2/8dm+GdyuvKl7CsA5VaXFl4EfGwtT+Sz8OPqSXkkiyYFPJySSXEbh0U3rxl9Y+wDmkpsg7eMJhXn9Szn1JGVbNzKwk/veBa/UWDwojRyXc/gICylHqDa+9UMNs2flw
  template:
    metadata:
      name: artifact-keeper-jwt-secret
      namespace: artifact-keeper
    type: Opaque
